name: charcode
version: 1.4.1
repository: https://github.com/lrhn/charcode
description: >-
  Constants for ASCII and common non-ASCII character codes.
  Integer constants corresponding to the code points of
  individual characters.

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.25.0
  lints: ">=3.0.0 <6.0.0"
