name: charcode
version: 1.2.0-nullsafety.3
description: >
  Constants for ASCII and common non-ASCII character codes.

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  test: ^1.16.0-nullsafety
  pedantic: ^1.10.0-nullsafety
